# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dimasmufid.com',
                'doc_host': 'https://dimasmufid.github.io',
                'git_url': 'https://github.com/dimasmufid/dimasmufid.com',
                'lib_path': 'dimasmufid.com'},
  'syms': {'dimasmufid.com.core': {'dimasmufid.com.core.foo': ('core.html#foo', 'dimasmufid.com/core.py')}}}
